### ISSUE TITLE
Basic system Initalize:

### ISSUE THREAD

**Issue by cameled** [BrainCoTech/zephyr#1]
- [x] zephyr modules add GD32F4xx_Firmware_Library
- [x] add gigadevice gd32f4xx soc
- [x] USART/UART
- [x] add gigadevice gd32f405x boards
- [x] gd32f405x support hello_world sample

**Comment by cameled** [comment]
Merge @nandojve work [ARM: Introduce gigadevice gd32f403](https://github.com/zephyrproject-rtos/zephyr/pull/38661) in here. If his PR have been merged, we need update our GD32F4xx Module again.
zephyr: https://github.com/BrainCoTech/zephyr/commit/74df681dc5a24ab56f74271f32c4af40514c43b4
hal_gigadevice: https://github.com/BrainCoTech/hal_gigadevice/commit/fca423bcad61befe0ada1c37e246058280612d3e

**Comment by nandojve** [comment]
Hello @cameled ,

Nice to see that your team is looking to use GD32 with Zephyr. We have been working to enable it and I hope we can help each other. The RFC can be read at https://github.com/zephyrproject-rtos/zephyr/issues/38657.

Until we get https://github.com/zephyrproject-rtos/zephyr/pull/38661 in main tree there could be some changes.

I would recommend you look at https://github.com/zephyrproject-rtos/hal_gigadevice/pull/1 to understand yaml files from your SoC version. It will be necessary to enable pinctrl on it.

I encourage your team to open PRs to upstream code.

**Comment by cameled** [comment]
Hi @nandojve

We have the plan to contribute GD32F405/407 and GD32F450 SoCs and GD32F450Z-EVAL board support to Zephyr project.

**Comment by nandojve** [comment]
Yes, but I may have access to a GD32F450-EVAL at principle. I know that more people is interested on GD32F450 and there will be more people involved. I can help with GD32F405/407 reviews. Since GD32F405/407 and GD32F450 uses same firmware API there is no issues to test code only with GD32F450 for the upstream.

**Comment by cameled** [comment]
Done with branch gd32f405.
